### ISSUE TITLE
AntiForgeryStrategiesCore.QueueTokensAntiforgeryAdditionalDataProvider fails to get token from context

### ISSUE THREAD

**Issue by vinayakmali84** [SNiels/AntiforgeryStrategiesCore#1]
I am using QueueTokensAntiforgeryAdditionalDataProvider for generating antiforgery tokens. But I am not able to read token from GetTokens() method in ValidateAdditionalData. Whereas I can see token value on view. 

Method code is mentioned below
```
private static List<string> GetTokens(HttpContext context)
{
            return context.Session.GetString(TokenKey)?.Split(';').ToList() ?? new List<string>();
}
```

Can you please suggest solution for this problem?

**Comment by Swimburger** [comment]
I'm sorry, I don't understand yet, can you clarify?

- What do you mean by seeing token value on view? Do you mean you can see the antiforgerytoken in a hidden input on your form?
- How is your AntiForgery, Session, and Caching configured in Startup.cs?

If possible, a reproduceable sample would be very helpful.

**Comment by Swimburger** [comment]
In this repository the session timeout is set to only 10s, so it's possible if you copied that setting over that your session is simply expiring faster than you are submitting the form or refreshing the page.
```csharp
            services.AddSession(options =>
            {
                options.IdleTimeout = TimeSpan.FromSeconds(10);
                options.Cookie.HttpOnly = true;
                options.Cookie.IsEssential = true;
            });
```

**Comment by vinayakmali84** [comment]
> In this repository the session timeout is set to only 10s, so it's possible if you copied that setting over that your session is simply expiring faster than you are submitting the form or refreshing the page.
> 
> ```cs
>             services.AddSession(options =>
>             {
>                 options.IdleTimeout = TimeSpan.FromSeconds(10);
>                 options.Cookie.HttpOnly = true;
>                 options.Cookie.IsEssential = true;
>             });
> ```

Thanks Swimburger, 
You are right, I increased session time to 60 second and I was able to test it. 
I want to customize antiforgerytoken with random seed number, which will be generated by third party quantum random number provider, to achieve maximum randomness. 
I was exploring "QueueTokensAntiforgeryAdditionalDataProvider" so that even if end user opens multiple tabs in browser, application should support and validate antiforgerytoken.

**Comment by Swimburger** [comment]
Great to hear, good luck!
